# Generated by Django 5.2.5 on 2025-08-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-scraped_at'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='scraped_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='platform',
            field=models.CharField(choices=[('YT', 'YouTube'), ('IG', 'Instagram'), ('TT', 'TikTok')], default='YT', max_length=2),
        ),
    ]
